openapi: 3.0.0

info:
  title: Jobs API

  contact: {}

  version: '1.0'

servers:
  - url: https://node-jobs-api-v1.herokuapp.com/api/v1

    variables: {}

paths:
  /auth/register:
    post:
      tags:
        - Auth

      summary: Register User

      operationId: RegisterUser

      parameters: []

      requestBody:
        description: ''

        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'

            example:
              name: example

              email: example@gemail.com

              password: secret

        required: true

      responses:
        '200':
          description: ''

          headers: {}

      deprecated: false

      security: []

  /auth/login:
    post:
      tags:
        - Auth

      summary: Login User

      operationId: LoginUser

      parameters: []

      requestBody:
        description: ''

        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUserRequest'

            example:
              email: example@email.com

              password: secret

        required: true

      responses:
        '200':
          description: ''

          headers: {}

      deprecated: false

      security: []

  /jobs:
    post:
      tags:
        - Jobs

      summary: Create Jobs

      operationId: CreateJobs

      parameters: []

      requestBody:
        description: ''

        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateJobsRequest'

            example:
              company: company name

              position: job position

        required: true

      responses:
        '200':
          description: ''

          headers: {}

      deprecated: false

      security:
        - bearer: []

    get:
      tags:
        - Jobs

      summary: Get All Jobs

      operationId: GetAllJobs

      parameters: []

      responses:
        '200':
          description: ''

          headers: {}

      deprecated: false

      security:
        - bearer: []

  /jobs/{id}:
    parameters:
      - in: path
        name: id # Note the name is the same as in the path
        required: true
        schema:
          type: string
        description: The job ID

    get:
      tags:
        - Jobs

      summary: Get Single Job

      operationId: GetSingleJob

      parameters: []

      responses:
        '200':
          description: ''

          headers: {}

      deprecated: false

      security:
        - bearer: []

    patch:
      tags:
        - Jobs

      summary: Update Job

      operationId: UpdateJob

      parameters: []

      responses:
        '200':
          description: ''

          headers: {}

      deprecated: false

      security:
        - bearer: []

    delete:
      tags:
        - Jobs

      summary: Delete Job

      operationId: DeleteJob

      parameters: []

      responses:
        '200':
          description: ''

          headers: {}

      deprecated: false

      security:
        - bearer: []

components:
  schemas:
    RegisterUserRequest:
      title: RegisterUserRequest

      required:
        - name

        - email

        - password

      type: object

      properties:
        name:
          type: string

        email:
          type: string

        password:
          type: string

      example:
        name: example

        email: example@gemail.com

        password: secret

    LoginUserRequest:
      title: LoginUserRequest

      required:
        - email

        - password

      type: object

      properties:
        email:
          type: string

        password:
          type: string

      example:
        email: example@email.com

        password: secret

    CreateJobsRequest:
      title: CreateJobsRequest

      required:
        - company

        - position

      type: object

      properties:
        company:
          type: string

        position:
          type: string

      example:
        company: company name

        position: job poition

  securitySchemes:
    bearer:
      type: http

      scheme: bearer

security: []

tags:
  - name: Misc

    description: ''

  - name: Auth

    description: ''

  - name: Jobs

    description: ''
